name: Build Luci-theme-design for OpenWrt

on:
  push:
    branches:
      - main

jobs:
  build_luci_apps:
    runs-on: ubuntu-latest

    env:
      EXTERNAL_REPO_URL: https://github.com/gngpp/luci-theme-design.git
      EXTERNAL_REPO_BRANCH: js
      PROGRAM_NAME: luci-theme-design
      OUTPUT_FILE: $PROGRAM_NAME
      RENAMED_FILE: Luci-theme-design

    steps:
    - name: Clone OpenWrt Repository
      run: |
        git clone https://github.com/openwrt/openwrt.git -b main /home/runner/openwrt

    - name: Clone Luci-theme-design Repository
      run: |
        git clone $EXTERNAL_REPO_URL -b $EXTERNAL_REPO_BRANCH /home/runner/openwrt/package/$PROGRAM_NAME

    - name: Add Luci Repository to feeds.conf.default
      run: |
        echo "src-git luci https://github.com/openwrt/luci.git" >> /home/runner/openwrt/feeds.conf.default

    - name: Install Dependencies for OpenWrt Build
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libpam0g-dev liblzma-dev libsnmp-dev

    - name: Compile Luci-theme-design
      run: |
        cd /home/runner/openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        make package/$PROGRAM_NAME/compile V=s

    - name: Rename Output File
      run: |
        mv /home/runner/openwrt/bin/packages/mips_24kc/packages/$OUTPUT_FILE.ipk /home/runner/openwrt/bin/packages/mips_24kc/packages/$RENAMED_FILE.ipk

    - name: Upload Renamed File
      uses: actions/upload-artifact@v2
      with:
        name: $RENAMED_FILE
        path: /home/runner/openwrt/bin/packages/mips_24kc/packages/$RENAMED_FILE.ipk
