name: Build Single Program for OpenWrt

on:
  push:
    branches:
      - main

jobs:
  build_single_program:
    runs-on: ubuntu-latest

    env:
      EXTERNAL_REPO_URL: https://github.com/gngpp/luci-theme-design.git
      EXTERNAL_REPO_BRANCH: js
      PROGRAM_NAME: Luci-theme-design
      OUTPUT_FILE: $PROGRAM_NAME
      RENAMED_FILE: Luci-theme-peditx

    steps:
    - name: Clone External Program Repository
      run: |
        git clone $EXTERNAL_REPO_URL -b $EXTERNAL_REPO_BRANCH package/$PROGRAM_NAME

    - name: Install Dependencies for OpenWrt Build
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Clone OpenWrt Repository
      run: |
        git clone https://github.com/openwrt/openwrt.git -b main /home/runner/openwrt

    - name: Update Feeds
      run: |
        cd /home/runner/openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Compile the Program
      run: |
        cd /home/runner/openwrt
        make defconfig
        make

    - name: Rename Output File
      run: |
        mv /home/runner/openwrt/$OUTPUT_FILE /home/runner/openwrt/$RENAMED_FILE

    - name: Upload Renamed File
      uses: actions/upload-artifact@v2
      with:
        name: $RENAMED_FILE
        path: /home/runner/openwrt/$RENAMED_FILE
