name: Build Luci-theme-design for OpenWrt

on:
  push:
    branches:
      - main

jobs:
  build_luci_theme:
    runs-on: ubuntu-latest

    env:
      EXTERNAL_REPO_URL: https://github.com/gngpp/luci-theme-design.git
      EXTERNAL_REPO_BRANCH: js
      PROGRAM_NAME: Luci-theme-design
      OUTPUT_FILE: $PROGRAM_NAME
      RENAMED_FILE: Luci-theme-peditx

    steps:
    - name: Clone Luci-theme-design Repository
      run: |
        git clone $EXTERNAL_REPO_URL -b $EXTERNAL_REPO_BRANCH /home/runner/$PROGRAM_NAME

    - name: Update feeds in Luci-theme-design repository
      run: |
        cd /home/runner/$PROGRAM_NAME/scripts
        ./feeds update -a
        ./feeds install -a

    - name: Install Dependencies for OpenWrt Build
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Compile Luci-theme-design
      run: |
        cd /home/runner/$PROGRAM_NAME
        make

    - name: Rename Output File
      run: |
        mv /home/runner/$OUTPUT_FILE /home/runner/$RENAMED_FILE

    - name: Upload Renamed File
      uses: actions/upload-artifact@v2
      with:
        name: $RENAMED_FILE
        path: /home/runner/$RENAMED_FILE
