name: Build Single Program for OpenWrt

on:
  push:
    branches:
      - main

jobs:
  build_single_program:
    runs-on: ubuntu-latest

    env:
      EXTERNAL_REPO_URL: https://github.com/gngpp/luci-theme-design.git
      EXTERNAL_REPO_BRANCH: main
      PROGRAM_NAME: Luci-theme-design
      OUTPUT_FILE: $PROGRAM_NAME
      RENAMED_FILE: Luci-theme-peditx.ipk

    steps:
    - name: Clone External Program Repository
      run: |
        git clone $EXTERNAL_REPO_URL -b $EXTERNAL_REPO_BRANCH

    - name: Install Dependencies for OpenWrt Build
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Compile the Program
      run: |
        cd $PROGRAM_NAME
        make

    - name: Rename Output File
      run: |
        mv $OUTPUT_FILE $RENAMED_FILE

    - name: Upload Renamed File
      uses: actions/upload-artifact@v2
      with:
        name: $RENAMED_FILE
        path: ./$RENAMED_FILE
